#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Project currently being analyzed👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

echo "Running ESLint..."
npm run lint

echo "Running Prettier..."
npm run format

if [ $? -ne 0 ]; then
  echo "Code linting or formatting issues found. Please fix them before committing."
  exit 1;
fi
